[package]
name = "css-core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "CSS parsing, cascade and matching without SpiderMonkey"

[lib]
path = "lib.rs"

[dependencies]
log = { workspace = true }
# CSS 解析（与 servo 同版本）
cssparser = { workspace = true }

[features]
default = []
